// ============================================
// Terms of Service — /terms
// ============================================

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — DealForge',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        {/* Back link */}
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: February 14, 2026
        </p>

        <div className="prose-sm mt-10 space-y-8 text-foreground/90 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_li]:text-muted-foreground">
          {/* 1 */}
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By creating an account or using DealForge (&quot;the Platform&quot;), you agree to be
              bound by these Terms of Service. If you do not agree, do not use the Platform.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2>2. Description of Service</h2>
            <p>
              DealForge is a web-based analysis tool that helps users evaluate potential real estate,
              business, and hybrid investment opportunities. The Platform provides financial
              calculations, projections, charts, PDF reports, and other analytical outputs based
              solely on data provided by the user.
            </p>
          </section>

          {/* 3 — the big one */}
          <section>
            <h2>3. No Financial, Legal, or Investment Advice</h2>
            <p>
              <strong>
                DealForge is an informational and educational tool only. Nothing on this Platform
                constitutes financial advice, investment advice, legal advice, tax advice, or any
                other form of professional advice.
              </strong>
            </p>
            <p>
              All projections, metrics, scores, analyses, charts, PDF reports, negotiation briefs,
              lender packets, and any other outputs generated by the Platform are estimates and
              approximations based on user-provided inputs and simplified models. They should not
              be relied upon as the sole basis — or a primary basis — for any purchase, sale,
              financing, or investment decision.
            </p>
            <p>
              You acknowledge and agree that:
            </p>
            <ul className="ml-4 list-disc space-y-2">
              <li>
                Investment decisions involve substantial risk, including the potential loss of
                your entire investment.
              </li>
              <li>
                Past performance, model projections, and hypothetical analyses do not guarantee
                future results.
              </li>
              <li>
                The Platform does not verify the accuracy or completeness of any data you provide.
              </li>
              <li>
                You are solely responsible for conducting your own independent due diligence before
                making any financial decision.
              </li>
              <li>
                You should consult qualified professionals — including financial advisors,
                accountants, attorneys, and licensed real estate professionals — before acting on
                any information from the Platform.
              </li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2>4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, DealForge and its creators,
              operators, affiliates, and contributors shall not be liable for any direct, indirect,
              incidental, consequential, special, or exemplary damages arising from or related to
              your use of the Platform — including but not limited to financial losses resulting
              from investment decisions influenced by Platform outputs.
            </p>
            <p>
              You agree that your use of the Platform is entirely at your own risk.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2>5. Accuracy of Information</h2>
            <p>
              While we strive to implement correct financial formulas and calculations, we make no
              warranties or representations regarding the accuracy, completeness, reliability, or
              suitability of any output generated by the Platform. Market data such as interest
              rates may be delayed, incomplete, or inaccurate.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2>6. User Responsibilities</h2>
            <p>
              You are responsible for the accuracy of all data you enter into the Platform. You
              agree not to rely on the Platform as a substitute for professional judgment or
              independent analysis. You are responsible for maintaining the confidentiality of
              your account credentials.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2>7. Intellectual Property</h2>
            <p>
              The Platform, including its design, code, and content, is protected by intellectual
              property laws. You may use reports and exports generated from your own data for
              personal and commercial purposes, but you may not reproduce, redistribute, or
              reverse-engineer the Platform itself.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2>8. Data and Privacy</h2>
            <p>
              Your deal data is stored in your account and is not shared with third parties. We
              use Firebase Authentication for account management and Firestore for data persistence.
              You may delete your data at any time by removing deals from your account.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2>9. Modifications to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the
              Platform after changes constitutes acceptance of the updated Terms. We will make
              reasonable efforts to notify users of material changes.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2>10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these Terms or
              that engage in abuse of the Platform. You may delete your account at any time.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2>11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              jurisdiction in which DealForge operates, without regard to conflict of law
              provisions.
            </p>
          </section>

          {/* Contact */}
          <section className="rounded-xl border border-border bg-card p-6">
            <h2>Questions?</h2>
            <p>
              If you have questions about these Terms, please reach out through the Platform&apos;s
              support channels.
            </p>
          </section>
        </div>

        {/* Footer */}
        <footer className="mt-12 border-t border-border pt-6 text-center text-xs text-muted-foreground">
          &copy; {new Date().getFullYear()} DealForge. All rights reserved.
        </footer>
      </div>
    </div>
  );
}
