// ============================================
// Share Deal as PDF — Shareable Link v1
// ============================================
// Generates a PDF blob URL and opens it in a new tab
// so the user can share/download/print. Also provides
// a "Copy PDF" action.

'use client';

import { useState } from 'react';
import { Share2, Check, Download, ExternalLink } from 'lucide-react';
import type { Deal } from '@/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { calcInvestmentScore } from '@/lib/calculations/score';
import { analyzeDeal } from '@/lib/analysis';

interface ShareDealButtonProps {
  deal: Deal;
}

// Minimal shared-view PDF builder (clean, no internal scores)
function buildShareablePDF(deal: Deal): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const DARK: [number, number, number] = [15, 23, 42];
  const BLUE: [number, number, number] = [30, 64, 175];
  const GRAY: [number, number, number] = [100, 116, 139];

  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

  const pct = (n: number) => `${n.toFixed(2)}%`;

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('DealForge — Deal Summary', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(16);
  doc.text(deal.name, pageWidth / 2, y, { align: 'center' });
  y += 7;

  const typeLabel = deal.dealType === 'real-estate' ? 'Real Estate' :
    deal.dealType === 'hybrid' ? 'Hybrid (RE + Business)' : 'Business Acquisition';

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(`${typeLabel} • Shared ${dateStr}`, pageWidth / 2, y, { align: 'center' });
  y += 4;

  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setTextColor(0);

  // Score summary
  const score = calcInvestmentScore(deal);
  const analysis = analyzeDeal(deal);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text(`Investment Score: ${score.total} — ${score.label}`, 14, y);
  y += 5;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(`Verdict: ${analysis.verdictLabel}`, 14, y);
  y += 8;

  doc.setTextColor(0);

  // Key details table
  const data = deal.data;
  const price = deal.dealType === 'real-estate' ? (data as { purchasePrice: number }).purchasePrice :
    deal.dealType === 'hybrid' ? (data as { purchasePrice: number }).purchasePrice :
    (data as { askingPrice: number }).askingPrice;

  const financing = data.financing;
  const overviewRows: string[][] = [
    ['Price', fmt(price)],
    ['Loan Amount', fmt(financing.loanAmount)],
    ['Down Payment', pct(financing.downPayment)],
    ['Interest Rate', pct(financing.interestRate)],
    ['Loan Term', `${financing.loanTermYears} years`],
  ];

  if (deal.tags.length > 0) {
    overviewRows.push(['Tags', deal.tags.join(', ')]);
  }

  autoTable(doc, {
    startY: y,
    head: [['Deal Overview', '']],
    body: overviewRows,
    theme: 'striped',
    headStyles: { fillColor: [...BLUE], fontStyle: 'bold' },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    margin: { left: 14, right: 14 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = ((doc as any).lastAutoTable?.finalY ?? y + 50) + 8;

  // Score breakdown
  const scoreRows = score.breakdown.map((c) => [
    c.name,
    `${Math.round(c.score)}`,
    `${(c.weight * 100).toFixed(0)}%`,
    `${c.weighted.toFixed(1)}`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Score Component', 'Score', 'Weight', 'Weighted']],
    body: scoreRows,
    theme: 'striped',
    headStyles: { fillColor: [...BLUE], fontStyle: 'bold', fontSize: 9 },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { halign: 'center' },
      2: { halign: 'center' },
      3: { halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by DealForge • ${dateStr} • View-Only Summary`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return doc;
}

export default function ShareDealButton({ deal }: ShareDealButtonProps) {
  const [copied, setCopied] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  function handleSharePDF() {
    const doc = buildShareablePDF(deal);
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setShowMenu(false);
  }

  function handleDownloadShare() {
    const doc = buildShareablePDF(deal);
    const safeName = deal.name.replace(/[^a-zA-Z0-9]/g, '_');
    doc.save(`${safeName}_summary.pdf`);
    setShowMenu(false);
  }

  async function handleCopyLink() {
    // Copy a text summary to clipboard as a shareable "link" alternative
    const score = calcInvestmentScore(deal);
    const price = deal.dealType === 'real-estate'
      ? (deal.data as { purchasePrice: number }).purchasePrice
      : deal.dealType === 'hybrid'
      ? (deal.data as { purchasePrice: number }).purchasePrice
      : (deal.data as { askingPrice: number }).askingPrice;

    const fmt = (n: number) =>
      new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

    const text = [
      `DealForge — ${deal.name}`,
      `Type: ${deal.dealType === 'real-estate' ? 'Real Estate' : deal.dealType === 'hybrid' ? 'Hybrid' : 'Business'}`,
      `Price: ${fmt(price)}`,
      `Score: ${score.total}/100 (${score.label})`,
      `Rate: ${deal.data.financing.interestRate}% / ${deal.data.financing.loanTermYears}yr`,
      '',
      'Download the full report from DealForge for detailed analysis.',
    ].join('\n');

    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    setShowMenu(false);
  }

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="flex items-center gap-1.5 rounded-lg border border-border px-4 py-2 text-sm font-medium text-foreground transition hover:bg-secondary"
        title="Share deal"
      >
        <Share2 className="h-4 w-4" />
        <span className="hidden sm:inline">Share</span>
      </button>

      {showMenu && (
        <>
          {/* Backdrop */}
          <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />

          {/* Dropdown */}
          <div className="absolute right-0 top-full z-50 mt-1 w-56 rounded-lg border border-border bg-card shadow-lg">
            <div className="p-1">
              <button
                onClick={handleSharePDF}
                className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground transition hover:bg-secondary"
              >
                <ExternalLink className="h-4 w-4 text-muted-foreground" />
                Open as PDF
              </button>
              <button
                onClick={handleDownloadShare}
                className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground transition hover:bg-secondary"
              >
                <Download className="h-4 w-4 text-muted-foreground" />
                Download Summary PDF
              </button>
              <button
                onClick={handleCopyLink}
                className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground transition hover:bg-secondary"
              >
                {copied ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Share2 className="h-4 w-4 text-muted-foreground" />
                )}
                {copied ? 'Copied!' : 'Copy Deal Summary'}
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
